### PR TITLE
[kernel] Fix w8a8 crash issue due to buffer size not big enough

### LINKED ISSUE #155: chatGLM2-6B crash while running  4 ranks with the datatype w8a8
With xFT1.2.0, running 4 ranks on HBM 1 socket. It works on using 1 rank.
bash run_benchmark.sh -m chatglm2-6b -d w8a8 -s 1 -bs 1 -in 1024 -out 32 -i 5

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 7633 RUNNING AT spr28
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 7634 RUNNING AT spr28
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 2 PID 7635 RUNNING AT spr28
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 3 PID 7636 RUNNING AT spr28
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================

### PR DESCRIPTION
**Pull request by xiangzez**
Fix #155

### CODE REVIEW

File: src/utils/matmul_helper.h [hunk 1]
```diff
@@ -492,11 +492,15 @@ class MMHelper {
...
         // W8A8
         else if constexpr (std::is_same_v<WeiT, w8a8_t>) {
-            weight.Resize(K, N);
             auto tag = trans ? dnnl::memory::format_tag::ba : dnnl::memory::format_tag::ab;
             dnnl::memory B_mem({{K, N}, dnnl::memory::data_type::s8, tag}, get_dnnl_engine(), src.Data());
-            dnnl::memory packedB_mem({{K, N}, dnnl::memory::data_type::s8, get_amx_s8s8s32_weight_data_type()},
-                    get_dnnl_engine(), weight.Data());
+            dnnl::memory::desc desc {{K, N}, dnnl::memory::data_type::s8, get_amx_s8s8s32_weight_data_type()};
+            // When converting to oneDNN blocked memory format, padded dims can be larger than [K, N]
+            // Resize down Matrix does not change underlying buffer.
```
Comment (pujiang2018) [inline src/utils/matmul_helper.h:499]: @xiangzez pls add a todo here (better to add some reserve like function in Matrix, as current 2 times Resize has risks in cases ...)

**Review by pujiang2018 — APPROVED** [review]
